version: '3.1'
services:
  wordpress:
    container_name: 'wp'
    build: .
    restart: unless-stopped
    links:
      - mysql
    env_file:
      - app.env
    volumes:
      - ./src/themes/:/var/www/html/wp-content/themes
      - ./src/plugins/:/var/www/html/wp-content/plugins
      - ./build:/build
      - "node-modules:/var/node_modules"
    ports:
      - 80:80
      - 3000:3000
      - 3001:3001
    command: /bin/bash -c "apache2-foreground & gulp"
  mysql:
    container_name: "wp-db"
    image: mysql
    restart: unless-stopped
    volumes:
       - ./build/sql:/build/sql
    env_file:
      - app.env
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
    - mysql:db
    restart: always
    ports:
     - 8080:80
volumes:
  node-modules:
